name: Build and Release Go Binaries

on:
  release:
    types: [published]

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [386, amd64, arm64]
        exclude:
          - goarch: 386
            goos: darwin
          - goarch: arm64
            goos: windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build binaries
        working-directory: ./src
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o activitypub-fw_${{ matrix.goos }}_${{ matrix.goarch }}

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: activitypub-fw_${{ matrix.goos }}_${{ matrix.goarch }}
          path: ./src/activitypub-fw_${{ matrix.goos }}_${{ matrix.goarch }}

  release:
    needs: compile
    name: Release to GitHub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [386, amd64, arm64]
        exclude:
          - goarch: 386
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: activitypub-fw_${{ matrix.goos }}_${{ matrix.goarch }}
          path: activitypub-fw_${{ matrix.goos }}_${{ matrix.goarch }}
      - uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: activitypub-fw_*